### ISSUE TITLE
import { User, Credentials, GraphQLConfig } crashes React app

### ISSUE THREAD

**Issue by ajonno** [realm/realm-graphql#10] opened 2018-02-04 09:05 UTC
Here are repro steps:
1. run create-react-app
2. install Apollo (just following their basic getting started, down to the "Describe your data" step; ```https://www.apollographql.com/docs/react/basics/setup.html```)
3. change the ```new ApolloClient(...``` to point to a ROS. eg.
```
const client = new ApolloClient({
  link: new HttpLink({ uri: 'http://xxx.yy.zzz.238:9080/graphql/TestRealm' }),
  cache: new InMemoryCache()
});
```
Also don't forget to wrap the top most div in the ```render()``` method with ```<ApolloProvider>```
eg.
```
return (
      <ApolloProvider client={client}>
        <div className="App">
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <h1 className="App-title">Welcome to React</h1>
          </header>
          <p className="App-intro">
            To get started, edit <code>src/App.js</code> and save to reload.
          </p>
        </div>
      </ApolloProvider>
    );
```

__Assuming setup is ok, you can pop a ```console.log``` in the ```client.query(..)```__
__and you'll see the data returned from ROS__

__UP TO HERE, ALL WORKS FINE__

4. Now, install ```realm-graphql-client```, ```apollo-client-preset apollo-link-ws subscriptions-transport-ws```

5. add this: ```import { User, Credentials, GraphQLConfig } from 'realm-graphql-client';```

__The React app will crash in the browser__

Here is the error I saw:
```
"ReferenceError: AuthenticationHelper is not defined↵    at eval (eval at webpackMissingModule (http://localhost:3000/static/js/bundle.js:46414:150), <anonymous>:1:1)↵    at webpackMissingModule (http://localhost:3000/static/js/bundle.js:46414:150)↵    at Object../node_modules/realm-graphql-client/dist/authenticationHelper.js (http://localhost:3000/static/js/bundle.js:46414:160)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at fn (http://localhost:3000/static/js/bundle.js:89:20)↵    at Object../node_modules/realm-graphql-client/dist/graphqlConfig.js (http://localhost:3000/static/js/bundle.js:46518:32)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at fn (http://localhost:3000/static/js/bundle.js:89:20)↵    at Object../node_modules/realm-graphql-client/dist/index.js (http://localhost:3000/static/js/bundle.js:46598:10)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at fn (http://localhost:3000/static/js/bundle.js:89:20)↵    at Object../src/App.js (http://localhost:3000/static/js/bundle.js:58046:80)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at fn (http://localhost:3000/static/js/bundle.js:89:20)↵    at Object../src/index.js (http://localhost:3000/static/js/bundle.js:58272:63)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at fn (http://localhost:3000/static/js/bundle.js:89:20)↵    at Object.0 (http://localhost:3000/static/js/bundle.js:58428:18)↵    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:679:30)↵    at ./node_modules/ansi-regex/index.js.module.exports (http://localhost:3000/static/js/bundle.js:725:37)↵    at http://localhost:3000/static/js/bundle.js:728:10
```

__package.json here:__
[package.json.zip](https://github.com/realm/realm-graphql/files/1692627/package.json.zip)

**Comment by ajonno** [comment] 2018-02-20 22:32
hi folks, just checking in on this. Is there an eta for a fix of ```realm-graphql-client``` ?

**Comment by olivereisenhut** [comment] 2018-02-23 16:47
It seems like the issue is caused by webpack. It tires to require a module in the authentication helper. 
<img width="591" alt="screen shot 2018-02-23 at 17 41 22" src="https://user-images.githubusercontent.com/9077573/36605575-6a70f5c0-18c1-11e8-911d-9e43d00f7ffd.png">
Maybe it would be better if fetch can be provided as optional argument like [the apollo-http-link ](https://www.apollographql.com/docs/link/links/http.html#options)?

**Comment by nirinchev** [comment] 2018-02-23 16:52
Thanks for investigating this! I think it should be easy to expose it as an optional field in the config. We'd definitely appreciate a PR that fixes it, otherwise I'll try to look into it soon :)

**Comment by olivereisenhut** [comment] 2018-02-23 16:55
Sure I'll try to provide a PR.

**Comment by ajonno** [comment] 2018-02-24 04:45
nice one thanks guys!

**Comment by ajonno** [comment] 2018-03-14 21:37
Hi all, just checking in on when this might be merged?

**Comment by Drivez** [comment] 2018-04-30 11:58
Hi, i get the same error as @olivereisenhut  when using it in node. I have imported node-fetch, but the same error is there. Trying to use vue.js

**Comment by ajonno** [comment] 2018-05-20 02:58
sorry about this but i could have sworn i saw an email(?) about this ticket and that a fix was made and ready for testing. searched my email but couldn't find. is there anything out there to test for this fix ? do we need to pull a specific branch/version of ROS ?

**Comment by nirinchev** [comment] 2018-05-20 07:55
We recently merged a PR from @olivereisenhut that worked around this issue, can you upgrade to the latest version and check if the problem is fixed for you?

**Comment by ajonno** [comment] 2018-05-20 09:43
hey, thanks for that. actually i just updated to the latest builds on ROS & JS client, ran a first test, and had success with both query and mutations. however i couldn't get subscriptions working (which may be my code error or a different issue). but definitely this particular issue (the crash) is resolved - many thanks!

**Comment by nirinchev** [comment] 2018-05-20 10:09
Glad to hear that! If you can't figure out the subscriptions, feel free to open a new issue and we'll take a look.

**Comment by ajonno** [comment] 2018-05-24 03:36
hi Nikola, i thought id post here as others will benefit too. firstly - the fix is fine and working for me in dev mode. however i just tried to run a prod build to deploy (```npm run build```) and got the following crash:

```
Failed to minify the code from this file:

 	./node_modules/realm-graphql-client/dist/authenticationHelper.js:13
```

detailed error log attached.

hopefully is easy fix appreciate if you can let me know.


[errorlog.zip](https://github.com/realm/realm-graphql/files/2033724/errorlog.zip)

**Comment by ajonno** [comment] 2018-05-24 03:39
Hi Nikola,

Apologies but seems to be one issue remaining on this ticket - which is npm run build is crashing due to an issue with authenticationHelper.js:13. 

 

I’ve updated the ticket here (still shows itself as closed atm) https://github.com/realm/realm-graphql/issues/10#issuecomment-390470467

 

 

Regards,

Angus Johnston

Lead Developer

SOGO Golf

Mob: +61 400 44 29 23

**Comment by nirinchev** [comment] 2018-05-24 07:54
@kneth do you have any clue what this could mean?

**Comment by olivereisenhut** [comment] 2018-05-24 08:08
Following [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) guide I would suggest to set ES5 in the `tsconfig.json` file for compiling. But I have to verify if it's working.

**Comment by olivereisenhut** [comment] 2018-05-24 08:34
I tested it with the `"target": "es5"` option and it worked for me. I could provide a PR.

**Comment by kneth** [comment] 2018-05-24 10:34
Happy to hear about your progress, and thanks for the link.

**Comment by ajonno** [comment] 2018-05-24 10:45
thanks for quick reply guys. @olivereisenhut  - i'm not using typescript in the React project so don't see a ```tsconfig.json``` to edit. is this something that needs to be done on Realm's side and then re-publish a new npm update to ```realm-graphql-client``` ?

**Comment by ajonno** [comment] 2018-05-25 11:07
@nirinchev any idea when this fix will go in ? we need to push the site to production as soon as possible. im happy to do any workaround/s while waiting if that is feasible?

**Comment by nirinchev** [comment] 2018-05-25 12:27
As I said, I'm not super familiar with React, but I tried changing the target of the typescript compiler to es5 and this is the package that got produced. Can you try removing the npm package and installing this one? If it works, I'll publish to npm later tonight.

[realm-graphql-client-1.2.0.tgz.zip](https://github.com/realm/realm-graphql/files/2039257/realm-graphql-client-1.2.0.tgz.zip)

Github doesn't support .tgz, which is why I zipped it. You should be able to unarchive and then `npm install` the .tgz.

**Comment by ajonno** [comment] 2018-05-26 07:06
No worries totally understand re React.  Ive tested the tgz / update: the build to prod (for React) works great. Thanks for the quick assistance really appreciated.

Cheers,
Angus

**Comment by nirinchev** [comment] 2018-05-29 11:21
Thanks for testing that! I pushed 1.2.0 to npm so this should hopefully resolve this issue 😅

**Closed by nirinchev** 2018-05-29 11:21 UTC
Labels: P:1 Required, T:Bug-Crash
